server:
  port: 8888
  shutdown: graceful
  servlet:
    encoding:
      enabled: true
      charset: utf-8
      force: true
    context-path: /api/nginx/
spring:
  application:
    name: nginx-gangster-master
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.118.130:3306/nginx-neo
    username: root
    password: Tv75aYT8@
    type: com.zaxxer.hikari.HikariDataSource

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      update-strategy: not_empty
  mapper-locations: classpath*:/mapper/*Mapper.xml